services:
  nginx-proxy:
    image: nginx:alpine

    volumes:
      - ./errors:/usr/share/nginx/html:ro
      - ./configs:/etc/nginx/conf.d

    ports:
      - "80:80"
      - "443:443"

    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true

